import { beforeEach, expect, it, vi } from 'vitest';
const s = vi.hoisted(() => ({ session: {}, send: vi.fn(), maintain: vi.fn(), allowed: true }));
vi.mock('Engine/SessionStorage.js', () => ({ default: s.session }));
vi.mock('Network/NetworkManager.js', () => ({ default: { sendPacket: s.send } }));
vi.mock('Network/PacketStructure.js', () => ({ default: { CZ: { STATUS_CHANGE: class {} } } }));
vi.mock('DB/Jobs/JobPropertyTable.js', () => ({ default: { 1: {}, 4258: { isFourthClass: true } } }));
vi.mock('UI/Components/GameTools/AdventureControlService.js', () => ({ maintainCurrentCharacter: s.maintain }));
import { createGameAttributes } from '../../src/UI/Game/GameAttributes.js';
import { characterStatValues, updateCharacterStat, recordCharacterStatResult } from '../../src/UI/Game/CharacterStats.js';
import { pointResetState, resetCharacterPoints } from '../../src/UI/Game/GamePointReset.js';
import { createAttributesPanel } from '../../src/UI/Mobile/game/AttributesPanel.js';
beforeEach(() => {
 vi.clearAllMocks(); s.allowed = true;
 s.session.Playing = true;
 s.session.Entity = { _job: 4258, action: 0, ACTION: { DIE: 99 }, life: { hp_max: 1000, sp_max: 100 } };
 for (const [key, value] of Object.entries({ str: 10, str2: 3, str3: 3, agi: 130, agi3: 0, vit: 20, vit3: 4, statuspoint: 3, pow: 4, pow3: 1, trait_point: 6, atak: 20, atak2: 5, patk: 2 })) updateCharacterStat(s.session.Entity, key, value);
});
it('spends only server-authorized costs and waits for its own acknowledgement without optimistic changes', () => {
 const service = createGameAttributes(() => s.allowed);
 expect(service.snapshot().base.rows.find(x => x.key === 'str')).toMatchObject({ value: 10, bonus: 3, cost: 3, canAdd: true });
 service.increase('base', 'agi'); service.increase('base', 'vit'); service.increase('related', 'str');
 expect(s.send).not.toHaveBeenCalled();
 service.increase('base', 'str'); service.increase('base', 'str');
 expect(s.send).toHaveBeenCalledExactlyOnceWith(expect.objectContaining({ statusID: 13, changeAmount: 1 }));
 expect(characterStatValues(s.session.Entity).str).toBe(10);
 recordCharacterStatResult(s.session.Entity, 14, true);
 expect(service.snapshot().pending).toBe(true);
 updateCharacterStat(s.session.Entity, 'str', 11); updateCharacterStat(s.session.Entity, 'atak', 21); updateCharacterStat(s.session.Entity, 'statuspoint', 0);
 recordCharacterStatResult(s.session.Entity, 13, true);
 const result = service.snapshot();
 expect(result.pending).toBe(false);
 expect(result.related.base.find(x => x.key === 'atak')).toMatchObject({ previous: '20 + 5', value: '21 + 5' });
 expect(result.base.rows[0].canAdd).toBe(false);
});
it('handles rejected allocation, connection/death guards and a different character', () => {
 const service = createGameAttributes(() => s.allowed);
 service.increase('traits', 'pow');
 expect(s.send).toHaveBeenCalledWith(expect.objectContaining({ statusID: 219 }));
 recordCharacterStatResult(s.session.Entity, 219, false);
 expect(service.snapshot().message).toContain('未成功');
 s.allowed = false; service.increase('traits', 'pow'); s.allowed = true;
 s.session.Playing = false; service.increase('traits', 'pow'); s.session.Playing = true;
 s.session.Entity.action = 99; service.increase('traits', 'pow');
 expect(s.send).toHaveBeenCalledTimes(1);
 s.session.Entity = { _job: 1, ACTION: { DIE: 99 } };
 expect(service.snapshot()).toMatchObject({ traits: { enabled: false }, message: '', pending: false });
 service.increase('traits', 'pow');
 expect(s.send).toHaveBeenCalledTimes(1);
});
it('resets base and traits separately, prevents overlapping resets and reports API failures', async () => {
 const service = createGameAttributes(() => s.allowed);
 let resolve;
 s.maintain.mockImplementationOnce(() => new Promise(r => { resolve = r; }));
 const first = service.reset('base');
 expect(service.snapshot().pending).toBe(true);
 expect(s.maintain).toHaveBeenCalledExactlyOnceWith('character.stats.reset', {});
 await service.reset('traits'); service.increase('base', 'str');
 expect(s.maintain).toHaveBeenCalledTimes(1); expect(s.send).not.toHaveBeenCalled();
 resolve({}); await first;
 expect(service.snapshot().message).toBe('基础素质点已重置');
 s.maintain.mockRejectedValueOnce(new Error('服务暂时不可用'));
 await service.reset('traits');
 expect(s.maintain).toHaveBeenLastCalledWith('character.traits.reset', {});
 expect(service.snapshot()).toMatchObject({ pending: false, message: '服务暂时不可用' });
 const old = s.session.Entity;
 s.maintain.mockImplementationOnce(() => new Promise(r => { resolve = r; }));
 const pending = resetCharacterPoints('skills', old);
 s.session.Entity = { _job: 1, ACTION: { DIE: 99 } };
 expect(pointResetState(s.session.Entity).pending).toBe(false);
 resolve({}); expect(await pending).toBe('角色会话已变更');
 expect(await resetCharacterPoints('base', old)).toContain('不能');
});
it('confirms resets, switches category safely and ignores late updates to a replaced panel', async () => {
 const body = document.createElement('div');
 const service = createGameAttributes(() => s.allowed);
 const reset = vi.spyOn(service, 'reset');
 const panel = createAttributesPanel(body, service);
 const click = text => [...body.querySelectorAll('button')].find(b => b.textContent === text).click();
 click('重置素质点'); expect(reset).not.toHaveBeenCalled();
 click('取消'); expect(body.querySelector('.point-reset-confirm').hidden).toBe(true);
 click('重置素质点'); click('四转素质');
 expect(body.querySelector('.point-reset-confirm').hidden).toBe(true);
 expect(body.querySelector('[data-attribute=pow]')).not.toBeNull();
 let resolve; s.maintain.mockImplementationOnce(() => new Promise(r => { resolve = r; }));
 click('重置素质点'); click('确认重置素质点');
 expect(reset).toHaveBeenCalledExactlyOnceWith('traits');
 expect([...body.querySelectorAll('.attribute-tabs button')].every(b => b.disabled)).toBe(true);
 body.textContent = '新的菜单'; resolve({});
 await vi.waitFor(() => expect(pointResetState(s.session.Entity).pending).toBe(false));
 panel.update(); expect(body.textContent).toBe('新的菜单');
});
it('hides the fourth-job tab for earlier jobs', () => {
 s.session.Entity._job = 1;
 const body = document.createElement('div'); createAttributesPanel(body, createGameAttributes(() => true));
 expect([...body.querySelectorAll('button')].find(b => b.textContent === '四转素质').hidden).toBe(true);
});
