import {beforeEach,it,expect,vi} from 'vitest';
const s=vi.hoisted(()=>({mobile:true,hooks:new Map(),pet:{append:vi.fn(),setInformations:vi.fn(),setIntimacy:vi.fn(),setHunger:vi.fn()},slot:{append:vi.fn(),setResult:vi.fn()},target:{append:vi.fn(),set:vi.fn(),TYPE:{PET:1}},items:{append:vi.fn(),setList:vi.fn(),setTitle:vi.fn()},session:{pet:{},petId:0},capture:vi.fn(),result:vi.fn(),eggs:vi.fn(),info:vi.fn(),state:vi.fn(),feed:vi.fn()}));
vi.mock('UI/Platform.js',()=>({default:{get isMobile(){return s.mobile;}}}));
vi.mock('UI/Game/GamePet.js',()=>({openGamePetCapture:s.capture,receiveGamePetCapture:s.result,openGamePetEggs:s.eggs,updateGamePetInfo:s.info,updateGamePetState:s.state,receiveGamePetResult:s.feed}));
vi.mock('UI/Components/PetInformations/PetInformations.js',()=>({default:s.pet}));
vi.mock('UI/Components/SlotMachine/SlotMachine.js',()=>({default:s.slot}));
vi.mock('UI/Components/SkillTargetSelection/SkillTargetSelection.js',()=>({default:s.target}));
vi.mock('UI/Components/ItemSelection/ItemSelection.js',()=>({default:s.items}));
vi.mock('UI/Components/PetEvolution/PetEvolution.js',()=>({default:{}}));
vi.mock('Engine/SessionStorage.js',()=>({default:s.session}));
vi.mock('Renderer/EntityManager.js',()=>({default:{get:()=>null}}));
vi.mock('UI/UIManager.js',()=>({default:{showPromptBox:vi.fn()}}));
vi.mock('UI/Components/ChatBox/ChatBox.js',()=>({default:{addText:vi.fn(),TYPE:{ERROR:0},FILTER:{PUBLIC_LOG:0}}}));
vi.mock('DB/DBManager.js',()=>({default:{getMessage:()=>'%s',getItemInfo:()=>({identifiedDisplayName:'食物'})}}));
vi.mock('Core/Client.js',()=>({default:{}}));
vi.mock('Network/NetworkManager.js',()=>({default:{sendPacket:vi.fn(),hookPacket:(type,fn)=>s.hooks.set(type,fn)}}));
vi.mock('Network/PacketStructure.js',()=>{const group=()=>new Proxy({}, {get:(t,k)=>t[k]||=(class{})});return{default:{CZ:group(),ZC:group()}};});
import initialize from '../../src/Engine/MapEngine/Pet.js';
import PACKET from 'Network/PacketStructure.js';
const receive=(name,pkt)=>s.hooks.get(PACKET.ZC[name])(pkt);
beforeEach(()=>{vi.clearAllMocks();s.mobile=true;s.session.petId=0;initialize();});
it('routes capture, eggs, status and feeding to mobile without mounting desktop controls',()=>{receive('START_CAPTURE',{});receive('TRYCAPTURE_MONSTER',{result:1});receive('PETEGG_LIST',{eggList:[2,3]});receive('CHANGESTATE_PET',{type:0,GID:20,data:0});expect(s.session.petId).toBe(20);receive('PROPERTY_PET',{job:1002});receive('FEED_PET',{cRet:0});expect(s.capture).toHaveBeenCalledOnce();expect(s.result).toHaveBeenCalledWith(1);expect(s.eggs).toHaveBeenCalledWith([2,3]);expect(s.info).toHaveBeenCalledWith({job:1002});expect(s.feed).toHaveBeenCalledWith('feed',0);expect(s.pet.append).not.toHaveBeenCalled();expect(s.target.append).not.toHaveBeenCalled();expect(s.items.append).not.toHaveBeenCalled();});
it('preserves desktop target, egg selector, status and capture animation routes',()=>{s.mobile=false;receive('START_CAPTURE',{});receive('TRYCAPTURE_MONSTER',{result:1});receive('PETEGG_LIST',{eggList:[2]});receive('PROPERTY_PET',{job:1002});expect(s.target.append).toHaveBeenCalledOnce();expect(s.slot.setResult).toHaveBeenCalledWith(1);expect(s.items.setList).toHaveBeenCalledWith([2]);expect(s.pet.append).toHaveBeenCalledOnce();expect(s.pet.setInformations).toHaveBeenCalledWith({job:1002});expect(s.info).not.toHaveBeenCalled();});
