// Audited against active Renewal NPC definitions for P0/P1 field maps.
// Runtime #... and ::... suffixes are preserved by DBManager.getNpcName().
export default {
	'???': '神秘人物',
	Acolyte: '服事',
	Ascetic: '修行者',
	Ashe: '艾什',
	'Assassin Guildsman': '刺客公会成员',
	Bard: '吟游诗人',
	"Bear's Footskin": '熊掌皮',
	Bergel: '贝尔格尔',
	'Bill of Birds': '鸟嘴',
	'Britoria Training Instructor': '布里托尼亚训练教官',
	'Broken Tools': '损坏的工具',
	'Bulletin Board': '公告栏',
	'Cactus Needles': '仙人掌刺',
	'Carpenter Firewood': '木匠的柴堆',
	Carrots: '胡萝卜',
	Cat: '猫',
	'Cat Paw Merchant Meraq': '猫手商人梅拉克',
	Chrysalis: '蛹',
	Chulho: '哲虎',
	'ClickClick MeowMeow-GX': '咔嗒喵喵-GX',
	'Clutter Traces': '杂物痕迹',
	'Continental Guard': '大陆卫队',
	'Culvert Guardian': '地下水道守卫',
	'Dimensional Gorge Piece': '次元裂隙碎片',
	Dvalin: '德瓦林',
	Eeyorbriggar: '伊约布里加',
	Emily: '艾米莉',
	Entomologist: '昆虫学家',
	'Feather of Bird': '鸟羽毛',
	Feathers: '羽毛',
	Fluff: '绵绒',
	'Gate Manager': '城门管理员',
	'Gemstone Bagger': '宝石装袋员',
	"Grasshopper's Legs": '蝗虫后腿',
	'Group of Evil': '邪恶聚合体',
	Guard: '卫兵',
	'Hidden Cave': '隐秘洞穴',
	Horns: '角',
	'Insect Feelers': '虫触角',
	'Investment Status Board': '投资状态公告板',
	Jellopy: '杰勒比结晶',
	'Kafra Employee': '卡普拉员工',
	Karian: '卡里安',
	'Lady Harvesting Herbs': '采药女子',
	'Lee Daegam': '李大监',
	'Mad Scientist': '疯狂科学家',
	"Magician's Guild Guide": '魔法师公会向导',
	'Map Examiner Gefil': '地图调查员杰菲尔',
	Mersetzdeitz: '梅尔塞茨代茨',
	'Mushroom Spores': '蘑菇孢子',
	'Mysterious Man': '神秘男子',
	Myu: '缪',
	'Nice Sweet Potato': '山药',
	'Odd Slab': '奇怪的石板',
	"Orc's Fangs": '兽人犬齿',
	'Pointed Scales': '尖锐鳞片',
	'Poring War Recruiter': '波利大战招募员',
	'Powder of Butterfly': '蝴蝶翅膀粉末',
	'Raccoon Leaf': '浣熊叶',
	'Red Herbs': '红色药草',
	Repairman: '修理工',
	Repherion: '雷菲里翁',
	'Reptile Tongues': '爬虫舌头',
	Resin: '树脂',
	'Resting Adventurer': '休息中的冒险者',
	'Rift Guard': '裂隙守卫',
	'Roda Frog': '罗达蛙',
	Roskva: '罗丝卡',
	'Royal Jelly': '蜂王浆',
	Salty: '萨尔蒂',
	'Scorpion Tails': '蝎子尾巴',
	Serutero: '瑟鲁特罗',
	Shorty: '肖蒂',
	Signpost: '告示牌',
	Signposts: '路标',
	"Snail's Shells": '蜗牛外壳',
	'Snake Scales': '蛇鳞',
	Soldier: '士兵',
	'Solid Shells': '坚硬外壳',
	Spawn: '产卵物',
	Stems: '茎',
	'Sticky Mucus': '黏液',
	'Sticky Webfoot': '黏糊的脚蹼',
	'Suspicious Light': '可疑的光芒',
	'Suspicious Man': '可疑男子',
	'Talking Dog': '会说话的狗',
	Talons: '爪子',
	'The Wanderer': '流浪者',
	'Time-Space Gap': '时空裂隙',
	'Tool Dealer': '道具商人',
	'Tree Roots': '树根',
	'Veggie Enchanter': '蔬菜附魔师',
	'Wolf Claws': '狼爪',
	'Worm Peelings': '蠕虫蜕皮',
	'Wrecked Cart': '损坏的手推车',
	Yesnelph: '耶斯奈尔夫',
	'Yoyo Tails': '狭盗猴尾巴',
	Zoologist: '动物学家'
};
