// Audited against active Renewal NPC definitions for the remaining P2 field maps.
// Runtime #... and ::... suffixes are preserved by DBManager.getNpcName().
export default {
	'=Notice=': '=告示=',
	Aas: '阿斯',
	AbyssWarp: '深渊湖入口',
	Adventurer: '冒险者',
	'Armor Dealer': '防具商人',
	'Artifact Appraiser': '神器鉴定师',
	'Artifact Enhancer': '神器强化师',
	Boat: '船',
	Burupu: '布鲁普',
	Column: '柱子',
	Daeguro: '戴古罗',
	'Dancer Kim': '舞者金',
	'Dispatched Instructor': '派驻教官',
	'Emergency Food Merchant': '应急食品商人',
	'Gemstone Bagger': '宝石装袋员',
	Girl: '女孩',
	Hallosu: '哈洛苏',
	'Heap of Earth': '土堆',
	Ishmael: '伊斯梅尔',
	Julian: '朱利安',
	'Kafra Employee': '卡普拉员工',
	Karian: '卡里安',
	'Kaya Tos': '卡娅·托斯',
	Lana: '拉娜',
	Lazy: '懒汉',
	'Map Examiner Bast': '地图调查员巴斯特',
	'Map Examiner Chakari': '地图调查员查卡莉娜',
	'Map Examiner Ciara': '地图调查员琪亚拉',
	'Map Examiner Dew': '地图调查员迪乌',
	'Map Examiner Huf': '地图调查员哈夫',
	'Map Examiner Kantu': '地图调查员坎图',
	'Map Examiner Lauren': '地图调查员劳伦',
	'Map Examiner Lipiri': '地图调查员利皮里',
	'Map Examiner Lucia': '地图调查员露西亚',
	'Map Examiner Modaka': '地图调查员莫达卡',
	'Map Examiner Rana': '地图调查员拉尼娅',
	'Map Examiner Shevko': '地图调查员谢夫科',
	'Map Examiner Sukumari': '地图调查员苏库玛丽',
	'Map Examiner Tailing': '地图调查员泰林',
	'Map Examiner Valenzela': '地图调查员瓦伦泽拉',
	'Map Examiner Yirun Seo': '地图调查员徐伊伦',
	Merchant: '商人',
	'Moks Bugs': '莫克斯虫',
	'Moks Mushrooms': '莫克斯蘑菇',
	'Mysterious Woman': '神秘女子',
	Passerby: '路人',
	'Postell Schuwell': '波斯特尔·舒维尔',
	Rahasu: '拉哈苏',
	'Rebellion Crew': '反叛军成员',
	'Reckless Explorer': '鲁莽的探险家',
	Rookie: '新人',
	Rope: '绳索',
	'Ruins Black Trader': '遗迹黑市商人',
	Sarumane: '萨鲁马内',
	'Secret Agent': '秘密特工',
	Signpost: '告示牌',
	Signposts: '路标',
	'Silk Sand Camel': '丝质沙漠骆驼',
	Spectator: '旁观者',
	'Stone Hearts': '石之心',
	'Striker Unit Commander': '突击部队指挥官',
	'Suspicious Heap of Earth': '可疑土堆',
	'Temporary Entrance': '临时入口',
	'Tool Dealer': '道具商人',
	"Torpy's Mom": '托尔皮的妈妈',
	'Tower Keeper': '塔楼看守',
	Traces: '痕迹',
	Traveler: '旅行者',
	Warp: '传送点',
	'Weapon Dealer': '武器商人',
	'Wincing Old Man': '面露痛苦的老人',
	'Wounded Man': '受伤男子',
	Zain: '扎因',
	Ziyaol: '吉奥尔',
	Zyosegirl: '海之少女',
	ein05_to_spcor: '特殊警戒区入口',
	toairplane: '飞艇入口'
};
