// Audited against active Renewal NPC definitions for midgame fixed dungeons.
// Runtime #... and ::... suffixes are preserved by DBManager.getNpcName().
export default {
	'3rdf_warp': '三层入口',
	'Blazing Fire': '熊熊烈火',
	'Bloody Knight Statue': '血色骑士雕像',
	'Blue Angel Statue': '蓝色天使雕像',
	'Brilliant Statue': '光辉雕像',
	'Bronze Statue': '青铜雕像',
	'Dark Devil Statue': '黑暗恶魔雕像',
	'Dispatched Instructor': '派驻教官',
	Elysia: '艾莉西亚',
	'Entrance Guide': '入口向导',
	Exit1: '出口',
	'Gold Religious Statue': '金色宗教雕像',
	'Green Wiseman Statue': '绿色贤者雕像',
	Guide: '向导',
	'Hot Land Surface': '灼热地表',
	'Illusion Stone Research': '幻象石研究',
	jupe_goto2F: '朱诺斯二层入口',
	lhz_dun03_lhz_dun04: '生体实验室四层入口',
	'lhz_dun5-1': '生体实验室三层入口',
	'Machine Statue': '机械雕像',
	'Man Stuck in Ice': '冰中男子',
	'Map Examiner Dove': '调查员多布',
	Maram: '马拉姆',
	'Red Flame': '红色火焰',
	'Rekenber Guard': '雷根贝勒卫兵',
	'Restricted Area': '禁区',
	'Rune Device': '符文装置',
	sanctuary01: '拉赫圣域随机传送点',
	Sculpture: '雕塑',
	'Shining Crystal': '闪耀水晶',
	'Spirit Detecting Staff': '精灵探测杖',
	'Splendid Sword': '华丽之剑',
	'Stone Statue': '石像',
	'Suspicious Monster': '可疑魔物',
	'to 7th Floor': '七层入口',
	'Trace of an adventurer': '冒险者的痕迹',
	'Unethical Machine': '非伦理机器'
};
