// Audited against active Renewal NPC definitions for remaining common fixed maps.
// Runtime #... and ::... suffixes are preserved by DBManager.getNpcName().
export default {
	'An entrance somewhere': '某处入口',
	Bear: '熊',
	enter_ein_dun03: '艾因贝赫矿山三层入口',
	Resident: '居民',
	'Teddy Bear': '玩具熊',
	'Entrance Device': '入口装置',
	'Heavy Door': '沉重的门',
	kh_dun04: '奇尔工厂四区入口',
	'Mechanical Device': '机械装置',
	Signboard: '告示牌',
	Biscuit: '饼干',
	'Chapped Skin': '干裂的皮肤',
	'Dry Skin': '干燥的皮肤',
	'Hard Skin': '坚硬的皮肤',
	'Linguist Devore': '语言学家德沃尔',
	'Map Examiner Mother One': '调查员马德尔翁',
	'Prickly Skin': '扎人的皮肤',
	'Star Candy': '星星糖',
	'Weird Entrance': '奇怪的入口',
	Books: '书籍',
	Creature: '生物',
	'Dead Crow': '乌鸦尸体',
	'Dead Man': '死者',
	Larjes: '拉尔杰斯',
	Man: '男子',
	Out_from_Monastery: '修道院出口',
	outtoin_01: '修道院入口',
	Signpost: '告示牌',
	'Trace of an adventurer': '冒险者的痕迹',
	Boatman: '船夫',
	'Valkyrie Illusion': '女武神幻影',
	warpinside: '神殿内部入口',
	'Young Man': '青年'
};
