// Audited against active Renewal NPC definitions for regional dungeons.
// Runtime #... and ::... suffixes are preserved by DBManager.getNpcName().
export default {
	Signpost: '告示牌',
	Soldier: '士兵',
	AyoFootprint1: '足迹1',
	AyoFootprint2: '足迹2',
	AyoFootprint3: '足迹3',
	AyoFootprint4: '足迹4',
	AyoFootprint5: '足迹5',
	AyoFootprint6: '足迹6',
	AyoFootprint7: '足迹7',
	AyoFootprint8: '足迹8',
	'Haggard Man': '阿农',
	Iara: '伊亚拉',
	Recluse: '贾西',
	'Gatekeeper of Krakatau': '克拉卡托火山守门人',
	'Spirit Detecting Staff': '精灵探测杖',
	'Strange dead body': '奇怪的尸体',
	'trace1-1': '痕迹1-1',
	'trace1-2': '痕迹1-2',
	'trace1-3': '痕迹1-3',
	'trace1-4': '痕迹1-4',
	'trace1-5': '痕迹1-5',
	'trace2-1': '痕迹2-1',
	'trace2-2': '痕迹2-2',
	'trace2-3': '痕迹2-3',
	'trace2-4': '痕迹2-4',
	'trace2-5': '痕迹2-5',
	'trace2-6': '痕迹2-6',
	'trace3-1': '痕迹3-1',
	'trace3-2': '痕迹3-2',
	'trace3-3': '痕迹3-3',
	'trace3-4': '痕迹3-4',
	'trace3-5': '痕迹3-5',
	'trace3-6': '痕迹3-6',
	'trace3-7': '痕迹3-7',
	'Baba Yaga': '芭芭雅嘎',
	Cow: '牛',
	'Gray Wolf': '灰狼',
	'Maria Morebna': '玛丽亚·莫雷布娜',
	'Noisy Coffin': '吵闹的棺材',
	Soldier1: '士兵',
	Soldier2: '士兵',
	Soldier3: '士兵'
};
