// Audited against active Renewal NPC definitions for the phase-two town maps.
// Internal #... and ::... suffixes are removed from keys and preserved at runtime.
export default {
	// aldebaran
	'Advanced Potion Merchant': '高级药水商人',
	'Alchemy Guy': '切米尔',
	'Ammunition Merchant': '弹药商人',
	'Armor Dealer': '防具商人',
	'Arrow Merchant': '箭矢商人',
	'Bell Keeper': '钟楼管理员',
	'Bill Thayer': '比尔·塞耶',
	'Bulletin Board': '艾尔帕兰：边境城市',
	'Canal Guy': '巴拿马',
	'Cat Paw Shrimp Merchant': '猫手虾商人',
	'Chef Assistant': '厨师助手',
	Citizen: '加文',
	'Continental Messenger': '大陆使者',
	'Cool Event Staff': '活动工作人员',
	Dolangmal: '多朗马尔',
	'Eden Teleport Officer': '乐园团空间传送员',
	Esseray: '埃瑟雷',
	'Forest Guy': '森林研究者',
	'Forger Munster': '蒙斯特',
	'Friendly-Looking Man': '和善的男子',
	'Fussy Man': '挑剔的男子',
	'Gemstone Bagger': '宝石装袋商',
	Guide: '向导',
	'Guild Warehouse Manager': '公会仓库管理员',
	Hohenschwangau: '霍恩施旺高',
	'Insect Guy': '昆虫研究者',
	Issei: '一诚',
	'Joo Jahk': '朱雀',
	'Kafra Employee': '卡普拉员工',
	'Kafra Jasmine': '卡普拉茉莉',
	'Kafra Service': '卡普拉服务员',
	'Kafra Teleportation': '卡普拉传送员',
	'Kafra Voting Staff': '卡普拉投票员',
	Karian: '卡里安',
	Lady: '女士',
	'Little Kid': '小孩',
	'Mado Gear Armorer': '魔导机甲整备员',
	'Mado Gear Merchant': '魔导机甲商人',
	Mailbox: '邮箱',
	'Maroll Battle Recruiter': '马洛尔战斗招募员',
	Master: '大师',
	Merchant: '商人',
	Meteurengut: '梅特伦古特',
	Monograph: '专著',
	'Monster Tamer': '魔物驯养师',
	'Mr. Claus': '克劳斯先生',
	Neuschwanstein: '新天鹅堡',
	'Ninja Tool Merchant': '忍者道具商人',
	Nuernberg: '纽伦堡',
	'Phracon Guy': '弗拉昆研究者',
	'Piru Piru': '皮鲁·皮鲁',
	'Point Merchant': '积分商人',
	'Promotional Staff': '宣传员',
	Repairman: '修理工',
	'Riding Creature Master': '坐骑管理员',
	'Rogue Agent': '流氓代理人',
	Rothenburg: '罗滕堡',
	'Royal Messenger': '王室使者',
	RS125: 'RS125 管理员',
	'Shell Gathering Lady': '乔安妮',
	Sign: '告示牌',
	Signposts: '路标',
	'Sir Jore': '乔尔爵士',
	'Slot Guy': '埃普希尔',
	'Smile Assistance': '微笑服务员',
	'Smithing Guy': '夸特罗',
	Sylvia: '西尔维娅',
	'Talisman Merchant': '符咒商人',
	'Threatening-Looking Man': '神情凶狠的男子',
	'Tool Dealer': '道具商人',
	'Town Girl': '城镇女孩',
	Trader: '商人',
	Tzerero: '特泽罗',
	'Weapon Dealer': '武器商人',
	Wuerzburg: '维尔茨堡',
	'Young Man': '米勒',
	'Zonda Teleportation': '赞达传送员',
	// yuno
	'A Citizen of Juno': '朱诺居民',
	'Active little girl': '活泼的小女孩',
	Adventurer: '冒险者',
	'Airship Representative': '飞艇代表',
	'Airship Staff': '飞艇职员',
	Alice: '爱丽丝',
	'Ambitious Hollgrehenn': '雄心勃勃的忽克连',
	'Ancient Mummy': '古代木乃伊',
	Andlangr: '安德朗格',
	'Ant Egg': '蚂蚁卵',
	'Apple of Idun': '伊登的苹果',
	Archeologist: '考古学家',
	Arclouz: '艾尔克诺兹',
	'Arivero Yurhik': '阿里维罗·尤里克',
	'Assistant Avery': '助理艾弗里',
	Assulter: '阿修罗狂战士',
	'Auction Hall Guide': '拍卖大厅向导',
	Bain: '贝恩',
	Bajin: '巴金',
	Basta: '巴斯塔',
	'Battle Songs': '战场鼓声',
	'Biology Professor': '卢修斯·凯尔苏斯',
	'Blacksmith Cleaver': '铁匠克利弗',
	Blazzer: '火焰妖',
	Book: '书籍',
	'Bundle of Files': '一捆文件',
	'Carbonated Water Vending Machine': '碳酸水自动售货机',
	Caterpillar: '狂暴螳螂',
	Chainheart: '链心',
	Chepet: '玩偶熊',
	CiCi: '茜茜',
	'Dean of the Academy': '凯隆·格里克',
	Degas: '德加',
	Delight: '德莱特',
	Deviace: '异变鱼',
	Dilemma: '迪莱玛',
	Dimir: '迪米尔',
	Doctor: '西尔奈尔',
	Dog: '狗',
	'Dragon Tail': '蜻蜓',
	Euslan: '尤斯兰',
	'Festival Manager': '庆典管理员',
	Freidrich: '弗雷德里希',
	Galapago: '果树龟',
	Geographer: '邪恶向日葵',
	'go away': '请勿靠近',
	Gomer: '戈默',
	'Hamerun, Rat Hunter': '捕鼠人哈梅伦',
	Himinn: '希敏',
	Historian: '历史学家',
	'History Professor': '萨菲恩·莱利斯',
	Hljod: '赫廖德',
	'Hot Bestseller Corner': '畅销书专区',
	Incubus: '梦魇',
	'Information Post': '信息公告牌',
	Irache: '伊拉切',
	'Juno Artisan': '工匠',
	'Juno Despot': '尼诺',
	'Juno Fighter': '塞尔吉奥夫',
	'Juno Granny': '老奶奶',
	'Juno Guide': '朱诺向导',
	'Juno Sage': '勒·莫菲斯',
	'Juno Soldier': '朱诺士兵',
	Kasis: '卡西斯',
	Kato: '卡托',
	Knight: '莱贝赫',
	Lambert: '兰伯特',
	'Library Master': '狗',
	'Library Part-Timer': '图书馆兼职生',
	"Luke's Songs Vol.1": '人生如水车',
	'Magical Item Seller': '魔法道具商人',
	'Male Thiefbug': '雄盗虫',
	Mandragora: '曼陀罗魔花',
	'Marine Sphere': '气泡虫',
	Megalodon: '邪骸海盗',
	Metto: '梅托',
	'Mighty Hammer': '神锤铁匠',
	Mischna: '米舒娜',
	'Mr. Click': '克里克先生',
	"Mr. King's Shop": '金先生的商店',
	'Museum Guide': '博物馆向导',
	Nehris: '内里斯',
	Noyee: '诺伊',
	'Odd Grandma': '古怪的老奶奶',
	'Old Blacksmith': '老铁匠',
	'Old Book': '旧书',
	'Old Lady': '老妇人',
	'Old Man': '老人',
	'Old News Scrapbook': '旧新闻剪报',
	'Owl Duke': '鸮袅男爵',
	Paper: '纸张',
	'Passionate Student': '班卡斯坦',
	'PecoPeco Egg': '大嘴鸟蛋',
	'Penniless Hollgrehenn': '身无分文的忽克连',
	Penomena: '裘卡',
	'Pet Groomer': '宠物美容师',
	'Physics Professor': '阿贝西·乔治',
	'Pile of Books': '一堆书',
	Pisruik: '皮斯鲁克',
	'Popular Feasts': '热门宴席',
	'Practical Examination P': '赫尔墨斯·特里斯',
	'Pub Master': '范特',
	Rafflesia: '捕虫堇',
	Raydric: '幽灵剑士',
	'Reading Girl': '读书女孩',
	'Red Book': '红色书籍',
	Representative: '代表',
	'Ride Word': '飞行魔书',
	'Rmimi Ravies': '瑞米米·拉维斯',
	Rosimmir_Entrance: '罗西米尔入口',
	'Sage Esklah': '贤者埃斯克拉',
	'Sage Syklah': '贤者西克拉',
	'Sage Worm': '贤者虫',
	'Sage Yklah': '贤者伊克拉',
	Scholar: '学者',
	Scroll: '卷轴',
	'Scroll Merchant': '卷轴商人',
	'Scrutiny Association': '监察协会',
	Seal: '封印',
	Skidbladnir: '斯基德普拉特尼',
	Sleeper: '泥人',
	'Staff of the Academy': '梅修斯·西尔菲',
	Stangckle: '斯坦克尔',
	'Stem Worm': '噬人花',
	Student: '乔伊·乔里',
	'Studying Scholar': '研究中的学者',
	Stylist: '造型师',
	Succubus: '魅魔',
	'Suspicious Man': '奥利弗·希尔珀特',
	'Teleport Prohibition equipment': '传送限制装置',
	'Thief Bug Egg': '盗虫卵',
	'Tri Joint': '三叶铁甲虫',
	Valerie: '瓦莱丽',
	Viblainn: '维布莱恩',
	Violy: '狂暴米洛斯',
	Wagan: '瓦甘',
	Wanderer: '浪人',
	'Worn-out Book': '破旧的书',
	'Written Test Professor': '克莱托斯·维尔多',
	'Yuno Prohibition equipment': '朱诺限制装置',
	Zhenbolt: '琴波特',
	// comodo
	Bafhail: '巴菲尔',
	'BBQ Boy': '烧烤少年',
	'BBQ Mama': '烧烤妈妈',
	'BBQ Papa': '烧烤爸爸',
	'BBQ Visitor': '烧烤访客',
	'Bor Robin': '博尔·罗宾',
	'Campground Boy': '罗奇托',
	'Campground Lad': '露营地少年',
	'Camping Maiden': '露营少女',
	'Camping Youth': '露营青年',
	Canell: '卡内尔',
	'Cheerless Maestro': '忧郁的音乐大师',
	Chief: '首领',
	'Comodo Guide': '科摩多向导',
	Deniroz: '德尼洛兹',
	Devellin: '德维林',
	'Dispatched Instructor': '派驻教官',
	'Emergency Exit': '出口',
	Examiner: '拉玛丁',
	'G . J': '吉·杰',
	Gatan: '加坦',
	'Hair Ornament Girl': '发饰女孩',
	Haith: '海思',
	Harive: '哈里夫',
	'Hat Girl': '帽子女孩',
	Hullaris: '胡拉里斯',
	Investigator: '调查员',
	Iriya: '伊莉雅',
	Kachua: '卡秋娅',
	'Kayak Master': '皮艇大师',
	Kichiri: '基奇里',
	'La Ed': '拉·艾德',
	Ledrion: '莱德里昂',
	Lospii: '洛斯皮',
	Loyar: '洛亚尔',
	Magatu: '马加图',
	Man: '男子',
	'Man in Hiding': '藏匿的男子',
	Manzi: '曼吉',
	Martine: '马丁',
	Meruntei: '梅伦泰',
	Moo: '穆',
	Muff: '穆夫',
	"Munak's Grandma": '僵尸女孩的奶奶',
	Niels: '尼尔斯',
	'Odd Switch': '奇怪的开关',
	'Ordinary Man': '普通男子',
	Rakusa: '拉库萨',
	Roberto: '罗伯托',
	'Rogue Guild Agent': '流氓公会代理人',
	s_dance: '舞蹈测试',
	s_dance_timer: '舞蹈计时器',
	Scoursege: '斯科尔斯',
	Shalone: '沙洛娜',
	'Small Safe': '小保险箱',
	Sonotora: '雅典娜·索诺托拉',
	'Souvenir Vendor': '纪念品商人',
	'Standby Room': '等候室',
	Stonae: '斯托娜',
	'Strange Guy': '迪尔斯',
	'Suspicious Guy': '凯恩',
	Toruna: '托鲁纳',
	Traveler: '旅行者',
	'Tropic Fruit Dealer': '热带水果商人',
	'Wandering Bard': '拉洛',
	'Wandering Master': '武刚',
	'Woman Roasting Meat': '烤肉女士',
	Won: '元',
	// rachel
	'?': '神秘人',
	'Abused Child': '受虐待的孩子',
	Amodipin: '阿莫迪平',
	'Assistant Mumuz': '助理穆穆兹',
	Banadis: '巴纳迪斯',
	'Bearded Jack': '大胡子杰克',
	'Black Marketeer': '黑市商人',
	Box: '箱子',
	'Cash Sales Guide': '商城向导',
	'Cheshrumnir Guard': '切斯鲁姆尼尔守卫',
	'Child Follower': '年幼信徒',
	'Common-Looking Man': '相貌普通的男子',
	'Cool Event Corp. Staff': '活动公司职员',
	Crowd: '围观群众',
	Cyr: '希尔',
	Dahil: '达希尔',
	Dina: '迪娜',
	Dream: '梦境',
	Dumplings: '饺子摊',
	Employee: '职员',
	'Fruit Gardener': '水果园丁',
	Gefn: '格芬',
	Girke: '吉尔克',
	Girl: '女孩',
	Grandma: '奶奶',
	'Greedy Man': '贪婪的男子',
	'Guant Prisoner': '关特囚犯',
	'Guard Gala': '守卫加拉',
	'Guard Izu': '守卫伊祖',
	'Half Flower': '半朵花',
	Hamion: '哈米恩',
	Hari: '哈里',
	'High Priestess Niren': '大祭司妮伦',
	Horn: '霍恩',
	imir3: '伊米尔装置',
	Ishira: '伊希拉',
	Japer: '贾珀',
	Jarad: '贾拉德',
	Jeojin: '乔金',
	Jesse: '杰西',
	Junok: '朱诺克',
	Karl: '卡尔',
	Katinshuell: '卡廷舒尔',
	Kid: '孩子',
	Kinos: '基诺斯',
	Lachellen: '拉切伦',
	Logan: '洛根',
	Lukshi: '卢克希',
	Magi: '马吉',
	Manson: '曼森',
	Maram: '马拉姆',
	Mardol: '马尔多尔',
	Mark: '马克',
	'Masked Girl': '蒙面女孩',
	'MealConversation Trigger': '服务员',
	Mejai: '梅贾伊',
	Miriam: '米里亚姆',
	Mohadian: '莫哈迪安',
	Molly: '莫莉',
	'Mr. Shendar': '申达先生',
	Naiman: '奈曼',
	'Nervous Priest': '紧张的祭司',
	Niren: '妮伦',
	'Niren Great Hall': '妮伦大厅',
	'Normal-Looking Man': '长相普通的男子',
	'Old Woman': '老妇人',
	'Ordinary Person': '普通人',
	'Oresa Rava': '奥蕾莎·拉瓦',
	Physics: '物理装置',
	'Post Box': '邮箱',
	Priest: '神殿守卫',
	'Rachel Guide': '拉赫向导',
	'Rare Diamond Merchant': '稀有钻石商人',
	Reminder: '提示牌',
	'Rhehe Ravies': '蕾赫·拉维斯',
	Rohi: '罗希',
	Sakjul: '萨克朱尔',
	Salesman: '销售员',
	Samariam: '萨马里安',
	'Seeking Follower': '阿鲁纳佩尔兹信徒',
	Senado: '塞纳多',
	Shiroan: '希罗安',
	Shopkeeper: '店主',
	'Sincere Follower Urstia': '乌斯蒂娅',
	Squain: '斯奎因',
	Suad: '苏阿德',
	'Suspicious-Looking Man': '看起来可疑的男子',
	Tamarin: '塔玛琳',
	'Temple Item Manager': '神殿道具管理员',
	Tiling: '地砖',
	'Trap Specialist': '陷阱专家',
	'Upset Looking Bard': '神情沮丧的吟游诗人',
	'Vegetable Gardener': '蔬菜园丁',
	Villager: '村民',
	Vincent: '文森特',
	Waiter: '服务员',
	Zed: '泽德',
	// veins
	'???': '神秘人物',
	'Assistant Eureka': '助理尤里卡',
	Bartender: '酒保',
	Bookshelf: '书架',
	Camel: '骆驼',
	Dandelion: '蒲公英',
	Drunkard: '醉汉',
	'Drunken Lady': '醉酒女士',
	'Drunken Man': '醉酒男子',
	Estillda: '艾斯蒂尔达',
	'Factory Manager': '米伦',
	'Factory Worker': '巴赫德',
	'Female Customer': '女顾客',
	Fighter: '斗士',
	Ivory: '有机肥皂制作者艾沃里',
	K: '凯',
	'King Crab': '帝王蟹',
	Lockenlock: '锁匠洛肯洛克',
	Magistrate: '阿尔·哈马德',
	'Male Customer': '男顾客',
	Peddler: '商贩',
	Saraman: '萨拉曼',
	'Sludge Worm': '污泥虫',
	Soldier: '士兵',
	'Strange Old Man': '阿布萨尔',
	Towner: '城镇居民',
	'Veins Guide': '维因斯向导',
	Vigilante: '巡逻队成员',
	Waitress: '女服务员',
	'Wall Closet': '壁橱',
	Ward: '沃德',
	'Young Merchant': '克雷夫',
	'Young Town Native': '当地青年',
	// einbroch
	'2nd Control Panel': '第二控制面板',
	'3rd Pressure Governor': '第三压力调节器',
	Aas: '阿斯',
	'Airship Engineer': '飞艇工程师',
	'Apprentice Researcher Sally': '见习研究员莎莉',
	'Arunafeltz Figure': '阿鲁纳佩尔兹人士',
	'Assistant Remain': '助理雷曼',
	'Bard Trigger': '吟游诗人事件',
	'Blacksmith Guildsman': '铁匠公会成员',
	'Blacksmith Jack': '铁匠杰克',
	'Bomb Maker': '炸弹制造师',
	Bouncer: '门卫',
	'Buender Hikeman': '本德尔·海克曼',
	Calla: '卡拉',
	Catzllanpu: '卡茨兰普',
	Cavitar: '卡维塔',
	Centzu: '森茨',
	Charity: '慈善募捐员',
	'Cheerful Dancer': '开朗的舞者',
	'Collapsed person': '倒地的人',
	Conveyor: '传送带',
	'Corporate Figure': '企业人士',
	'Coughing young man': '咳嗽的年轻人',
	Decii: '德西',
	"Ei'felle": '艾菲尔',
	'Einbech Guide': '艾因贝赫向导',
	'Einbech Prohibition equipment': '艾因贝赫限制装置',
	'Einbroch Guide': '艾因布洛克向导',
	'Einbroch Prohibition equipment': '艾因布洛克限制装置',
	'Einbroch Smog Alert': '艾因布洛克烟雾警报器',
	Ekuri: '艾库里',
	'Elle Cherno': '艾尔·切尔诺',
	Ellhenje: '艾尔亨杰',
	'Empty bench': '空长椅',
	'Enormous stack': '巨大的堆积物',
	Ferlock: '费洛克',
	'Flower Girl': '卖花女孩',
	'Flu Mask Dealer': '防毒面具商人',
	Franz: '弗朗茨',
	Galan: '加兰',
	Gonie: '戈尼',
	Guildsman: '公会成员',
	Gushenmu: '古申穆',
	Hander: '汉德尔',
	'Hotel Employee': '旅馆职员',
	'Hotel Manager': '旅馆经理',
	'Huge Tree': '大树',
	Jung: '荣格',
	Kaijeta: '凯杰塔',
	'Kaya Tos': '卡娅·托斯',
	Keneshiotz: '凯内希奥茨',
	Kesunboss: '凯森博斯',
	Khemko: '凯姆科',
	Khetine: '凯蒂娜',
	Khowropher: '科罗弗',
	Klitzer: '克利策',
	lab03: '安全系统',
	'Laboratory Guard': '实验室守卫',
	'Laboratory Soldier': '实验室士兵',
	Lazy: '懒汉',
	Leslie: '莱斯利',
	Liotzburg: '利奥茨堡',
	'Little Toby': '小托比',
	Luda: '露达',
	Maid: '女仆',
	'Main Control Panel': '主控制面板',
	Manthasman: '曼塔斯曼',
	Matestein: '马特斯坦',
	'Mature Looking Dancer': '成熟的舞者',
	Megass: '梅加斯',
	Metelle: '梅特尔',
	Mirror: '镜子',
	Mjunia: '穆尼娅',
	Mogan: '莫甘',
	Morei: '莫雷',
	Morriphen: '莫里芬',
	'Need help': '求助者',
	nemi: '内米',
	Nemuk: '尼穆克',
	Nihil: '尼希尔',
	Oberu: '奥贝鲁',
	'One Hand Weapon Dealer': '单手武器商人',
	Paddler: '划船人',
	'Paul Spanner': '保罗·斯帕纳',
	Philopontess: '菲洛蓬特斯',
	Pipe: '管道',
	Raust: '劳斯特',
	'Rebellion Crew': '反叛军成员',
	Rookie: '新人',
	'Ryan Danger': '莱恩·丹杰',
	Satra: '萨特拉',
	Scientist: '科学家',
	Security: '警卫',
	Shena: '谢娜',
	'Sick Old Man': '生病的老人',
	Signpost: '艾因贝赫地下城 1层',
	'Site manager Elmen': '现场管理员艾尔门',
	Skia: '斯琪亚',
	'Sleepy Looking Old woman': '困倦的老妇人',
	Sleik: '斯莱克',
	Supineque: '苏皮内克',
	Tan: '谭',
	'Tarsha Cherno': '塔莎·切尔诺',
	'Tavern Lady': '酒馆女主人',
	'Theo Cherno': '西奥·切尔诺',
	'Tired Looking Man': '疲惫的男子',
	'Tired Looking Old man': '疲惫的老人',
	Tirehaus: '蒂尔豪斯',
	Tollaf: '托拉夫',
	'Train Station Manager': '火车站管理员',
	'Train Station Staff': '火车站职员',
	Tree: '树木',
	'Two Hand Weapon Dealer': '双手武器商人',
	'Unidentified Machine': '不明机器',
	'Unknown Stuff': '不明物体',
	'Unusual person': '奇怪的人',
	'Uwe Kleine': '乌韦',
	'Very small hole': '很小的洞',
	'Young Dancer': '年轻舞者',
	Zelmeto: '泽尔梅托',
	// lighthalzen
	'A File': '一份文件',
	'A kid with black finger': '手指发黑的孩子',
	'A Pile of Paper': '一叠文件',
	Abduction_trigger: '绑架事件触发器',
	Alchemist: '炼金术师',
	Annette: '安妮特',
	'Area 1-5': '区域 1-5',
	'Area 1-7': '区域 1-7',
	'Area 3-2': '区域 3-2',
	'Area 3-3': '区域 3-3',
	'Area 6-1': '区域 6-1',
	Arthur: '亚瑟',
	'Assistant Staff': '助理职员',
	Aures: '奥雷斯',
	Avetis: '阿维蒂斯',
	'Bad Drunk': '加里',
	'Bank Clerk': '银行职员',
	'Bankri Kun': '班克里·昆',
	'Banquet Staff': '宴会厅职员',
	Beggar: '乞丐',
	"Beginner's Merchant": '新手商人',
	'Ben Allen': '本·艾伦',
	Beninne: '贝宁',
	Berru: '比莉亚',
	Blackboard: '黑板',
	Bodger: '博杰',
	Broncher: '布朗彻',
	Bully: '恶霸',
	Butcher: '肉商',
	'Cenku Dekdam': '岑库·德卡姆',
	'Chief Secretary': '首席秘书',
	'Christopher Michael': '克里斯托弗·迈克尔',
	'City Girl': '城市女孩',
	Collins: '柯林斯',
	'Commander Arquien': '阿尔奎恩指挥官',
	'Commander Est': '艾斯特指挥官',
	'Cool Event Corp Staff': '活动公司职员',
	'Cool Event Manager': '活动经理',
	Crevice: '裂缝',
	'Crippled Girl': '跛脚女孩',
	Crux: '克鲁克斯',
	Customer: '顾客',
	'Dan Song': '丹松',
	Delna: '德尔娜',
	Diana: '戴安娜',
	Digotz: '迪戈茨',
	'Doll Supplier': '玩偶供应商',
	Dono: '多诺',
	Door: '门',
	'Dowbow Ryuei': '道博·龙英',
	Eiya: '艾娅',
	Elder: '长老',
	Ellette: '艾莱特',
	'Elmer Keays': '埃尔默·凯斯',
	Emily: '艾米莉',
	Enoz: '埃诺兹',
	'Enquro Carson': '恩奎罗·卡森',
	'Equipment Reform PR Agent': '装备改造宣传员',
	'Event Planner': '活动策划员',
	'F. Harrison': 'F·哈里森',
	'File Search Engine': '文件检索装置',
	Fishbone: '鱼骨',
	Fruel: '弗鲁埃尔',
	Fulerr: '富勒',
	Gerhart: '格哈特',
	'Giacomo Girolamo': '贾科莫·吉罗拉莫',
	'Gift Merchant': '礼品商人',
	Gopal: '戈帕尔',
	Gracie: '格蕾西',
	'Greedy Looking Man': '神情贪婪的男子',
	Grinnel: '格林内尔',
	Guard: '守卫',
	Haggar: '哈格尔',
	'Hair Dyer': '染发师',
	Hanccet: '汉塞特',
	Harp: '哈普',
	'Healthy Looking Guy': '气色健康的男子',
	Helen: '海伦',
	Hinkley: '欣克利',
	'Housemaid Brenda': '女仆布伦达',
	'Housemaid Jane': '女仆简',
	HuMSpawner: '人类实验体生成器',
	'Ian Atnad': '伊恩·阿特纳德',
	Jade: '杰德',
	Janice: '珍妮丝',
	Jay: '杰伊',
	Jeweler: '珠宝商',
	Jiwon: '智媛',
	Jorje: '乔治',
	Jorjerro: '约书亚',
	Joshua: '约书亚',
	Joyce: '乔伊丝',
	Kariya: '卡里亚',
	'Kejulle Rekenber': '凯朱尔·雷根贝勒',
	Kellasus: '凯拉苏斯',
	Kemp: '肯普',
	Keshibien: '凯希比恩',
	Kimmy: '吉米',
	Klaubis: '克劳比斯',
	Koring: '科林',
	Kosit: '科西特',
	Krongast: '苏伊·斯莉尔',
	Krugg: '克鲁格',
	'Lab Staff': '阿萨姆',
	Laqumet: '拉克梅特',
	'Law Enforcement': '治安人员',
	Leablem: '利亚布雷姆',
	Leekal: '忍乔斯',
	Leimi: '蕾米',
	lhz_to_rekenber: '雷根贝勒入口',
	'Lighthalzen Guide': '莱茵哈特向导',
	'Little girl': '小女孩',
	Loudmouth: '大嘴',
	Luccet: '卢塞特',
	Lucius: '卢修斯',
	'Luke Lapez': '卢克·拉佩兹',
	'Mad Scientist': '沃尔切夫',
	Maggie: '玛吉',
	'Maintenance Guy': '维护人员',
	Maivi: '梅维',
	Makkie: '麦琪',
	Maku: '马克',
	Mareth: '马雷斯',
	'Margaret Mary': '玛格丽特·玛丽',
	'Margie Keays': '玛吉·凯斯',
	'Martial Artist': '武术家',
	Mauro: '毛罗',
	Mazwon: '马兹翁',
	'Member of Alliance': '联盟成员',
	Mereth: '梅雷斯',
	Merpi: '梅尔皮',
	Millette: '米莱特',
	Munkenro: '蒙肯罗',
	Nannan: '南南',
	Nemil: '内米尔',
	Ninjose: '忍乔斯',
	Noama: '诺阿玛',
	Nun: '安吉拉',
	'Officer A': '官员 A',
	'Officer B': '官员 B',
	'Officer Guo': '郭警官',
	'Ohno Tohiro': '大野十郎',
	Oyoung: '欧勇',
	Pat: '帕特',
	"Pat's Father": '帕特的父亲',
	"Pat's Mother": '帕特的母亲',
	Pilia: '皮莉娅',
	'Poison Herb Merchant': '毒草商人',
	Protester: '抗议者',
	Ravey: '拉维',
	Recruiter: '招募员',
	'Regenschirm Guard': '雷根贝勒卫兵',
	'Rekenber Chairman': '雷根贝勒董事长',
	'Rekenber Employee': '雷根贝勒职员',
	'Rekenber Guard': '雷根贝勒卫兵',
	'Rekenber Guard Drew': '雷根贝勒守卫德鲁',
	'Rekenber Guard Oscar': '雷根贝勒守卫奥斯卡',
	'Rekenber Guard Tan': '雷根贝勒守卫谭',
	'Rekenber Guidebook': '雷根贝勒指南',
	'Relaxed-Looking Lady': '神态悠闲的女士',
	'Republic Guard': '共和国守卫',
	Researcher: '研究员',
	Reuben: '鲁本',
	'Rihrtarzen Prohibition equipment': '里希塔乐镇限制装置',
	Rocky: '洛奇',
	Ruth: '露丝',
	'Safwat Fahmy': '萨夫瓦特·法赫米',
	Sameer: '萨米尔',
	Samnang: '三郎',
	Secretary: '秘书',
	'Secretary Slierre': '苏伊·斯莉尔',
	Sefith: '塞菲斯',
	Seiyablem: '塞亚布雷姆',
	Sergei: '谢尔盖',
	'Sewer Pipe': '下水管道',
	Shayna: '谢娜',
	Shengwen: '盛文',
	'Shop Assistant': '店员',
	Sigmund: '西格蒙德',
	Sikaiz: '西凯兹',
	Skrajjad: '斯克拉贾德',
	Sopheap: '索菲普',
	'Spica Nerius': '斯皮卡·内里乌斯',
	Srinivas: '斯里尼瓦斯',
	Staff: '职员',
	Sung: '成',
	Suspect: '嫌疑人',
	'Suspicious mercenary': '可疑的佣兵',
	Switch: '盖尔斯坦',
	Tadem: '塔德姆',
	Tanoue: '田上',
	Timer_Sneak: '潜入计时器',
	Togii: '托吉',
	'Toy Supplier': '玩具供应商',
	'Vendor from Milk Ranch': '牧场牛奶商人',
	Vergil: '维吉尔',
	'Veteran Adventurer': '资深冒险者',
	'Victor Perfecto': '维克托·佩尔费克托',
	Villagomez: '维拉戈麦斯',
	Wallace: '华莱士',
	'Wand Dealer': '法杖商人',
	'Wedding Shop Dealer': '婚礼用品商人',
	'Weird old man': '怪老头',
	'Windmill Owner': '米尔斯',
	"Windmill Owner's Helper": '克茨',
	// hugel
	'A Part-Timer': '兼职生',
	alex: '亚历克斯',
	Alex: '亚历克斯',
	'Allen Schuwell': '艾伦·舒维尔',
	Ashe: '艾什',
	Bismarc: '俾斯麦',
	Boatman: '船夫',
	'Booboo the Cow': '布布',
	'Bow Dealer': '弓箭商人',
	"Burupu's Instructions": '布鲁普的说明',
	'Cellette Lavit': '塞莱特',
	Chris: '克里斯',
	Clam: '蛤蜊',
	'Eckar Ellebird': '埃卡尔·埃尔伯德',
	'Eckar Erenes': '埃卡·埃雷尼斯',
	'El Schatt': '艾尔·沙特',
	Empty: '空位',
	Entrance: '入口',
	Erjan: '埃尔扬',
	'Falcon Breeder': '猎鹰饲养员',
	'Falcon Flute Trader': '猎鹰笛商人',
	Ghenirhemin: '格尼尔赫敏',
	'Guide Rich King': '富有的国王',
	'Guild Receptionist': '公会接待员',
	Herico: '赫里科',
	'Hugel Guide Granny': '休尔赫尔姆向导奶奶',
	'Inn Maid': '旅馆女仆',
	Julian: '朱利安',
	Kayplas: '凯普拉斯',
	Kurupe: '库鲁佩',
	Laura: '劳拉',
	Layoma: '拉约玛',
	Lisa: '丽莎',
	Maewan: '梅万',
	Manainne: '曼艾恩',
	Marius: '马里乌斯',
	'Monster Race Manager': '魔物竞速管理员',
	Mudie: '穆迪',
	Neha: '内哈',
	'Old Nikki': '老尼基',
	'Party Supplies Shop': '商店老板',
	Perfitz: '佩尔菲茨',
	'Postell Schuwell': '波斯特尔·舒维尔',
	'Praying Nun': '祈祷的修女',
	'Pub Granny': '酒馆老奶奶',
	Shede: '谢德',
	Siria: '西莉娅',
	'Strange Man': '奇怪的男子',
	'Suspicious Barrel': '可疑的木桶',
	toairplane: '飞艇入口',
	'Tone-deaf person': '音痴的人',
	Torpy: '托尔皮',
	'Upper Drawer': '上层抽屉',
	'Vacant Looking Lady': '神情空洞的女士',
	Wayne: '韦恩',
	// Associated guild, castle, temple, airport and quest maps
	'Guild Dealer': '公会商人',
	en_turbo: '竞速入口',
	'Turbo Track Guide': '涡轮赛道向导',
	'Muscle Man': '肌肉男',
	Buzz: '巴兹',
	Lenya: '莱妮娅',
	Gealuve: '吉洛夫',
	Pariz: '帕里斯',
	'Kafra Staff': '卡普拉职员',
	Alfredo: '阿尔弗雷多',
	Treasure: '宝箱',
	Agit: '城堡管理员',
	Guardian: '守护者',
	Chenchenlie: '陈晨莉',
	Nahzarf: '纳扎夫',
	Brymhensen: '布林汉森',
	Esmarehk: '埃斯马雷克',
	'Alchemist Guildsman': '炼金术师公会成员',
	'Fastidious Alchemist': '挑剔的炼金术师',
	'Studying Man': '研究中的男子',
	'Experiment Expert': '实验专家',
	'Master Alchemist': '炼金术大师',
	'Chief Researcher': '首席研究员',
	'aldeg-4-15_aldeg-4-': '露依纳城堡通道',
	'Sorin of Kafragarten': '卡普拉花园的索琳',
	'Defolty of Kafragarten': '卡普拉花园的德芙蒂',
	'Craft Book Merchant': '制作书商人',
	'ClickClick MeowMeow-GX': '咔嗒喵喵-GX',
	'Material Seller': '材料商人',
	'Mount Manager': '坐骑管理员',
	'Cat Paw Merchant Megrez': '猫手商人梅格雷兹',
	'Gate Manager': '城门管理员',
	'Investment Status Board': '投资状态公告牌',
	Glaris: '格拉里斯',
	Defolty: '德芙蒂',
	Sorin: '索琳',
	Bennit: '本尼特',
	W: '达布留',
	'Luina Training Instructor': '露依纳训练教官',
	'Alchemist Union Member': '炼金术师联盟成员',
	'Alliance Manager': '联盟管理员',
	Nuria: '努莉娅',
	Sippie: '西比',
	'Female Follower': '女性信徒',
	'Temple Entrance': '神殿入口',
	Nemma: '内玛',
	zawa00: '神殿通道',
	'High Priest Zhed': '大神官杰德',
	Panno: '潘诺',
	"Pope's Office Guard": '教皇办公室守卫',
	gyoin1: '神殿引导员',
	'Male Follower': '男性信徒',
	Priestess: '女祭司',
	Pope: '教皇',
	out1: '神殿出口',
	hidden1: '隐藏通道',
	key1: '钥匙装置',
	saint1: '圣域入口',
	'Rachel Guard': '拉赫守卫',
	'Flower Vase': '花瓶',
	path_vol1: '神殿通道',
	vol_time: '神殿计时器',
	vol_time2: '神殿计时器 2',
	Drawer: '抽屉',
	'Goddess Statue': '女神像',
	Ladder: '梯子',
	'Rookie Guard': '新任守卫',
	'Guard Calsort': '守卫卡尔索特',
	'Heart Hunter': '心脏猎手',
	'Marshal Chive': '统帅查夫',
	Eridanus: '艾利达努斯',
	'Guard Dent': '守卫登特',
	'Guard Neil': '守卫尼尔',
	'Priest Freya': '祭司芙蕾雅',
	Rachelite: '拉赫居民',
	'Rachel Resident': '拉赫居民',
	'Temple Knight': '神殿骑士',
	"Elly's Figure": '艾莉的身影',
	'Airport Staff': '机场职员',
	'Arrival Staff': '抵达处职员',
	File: '文件'
};
