export default {
	'Academy Student': '学院学生',
	Airship: '飞艇',
	Aram: '阿拉姆',
	Arena: '竞技场',
	'Black Shadow': '菲希',
	'Boarding Attendant': '登船服务员',
	Bonne: '博讷',
	Boozer: '酒鬼',
	'Captain of Anchovy Fish': '凤尾鱼号船长',
	'Cat Paw Service': '猫手商会',
	Cebalis: '塞巴利斯',
	'Channel Warp Official': '分流传送员',
	Charfri: '查弗里',
	'Chief Peperoncino': '佩佩罗奇诺首领',
	'Crewman of Anchovy Fish': '凤尾鱼号船员',
	'Criatura Academy Staff': '亨',
	'Cultivated Red Plant': '栽培的红色植物',
	Cuskoal: '库斯科尔',
	'Cute Baby': '戈帕拉',
	Daldal: '达尔达尔',
	Dad: '爸爸',
	Dega: '德加',
	'Doram On The Journey': '旅行中的杜拉姆',
	Edgar: '埃德加',
	Eggling: '蛋灵',
	'Emergency Patient': '急诊患者',
	'Enchanter Almond J': '附魔师阿尔蒙德·J',
	'Enchanter Mounds': '附魔师芒兹',
	Etinifni: '埃廷尼夫尼',
	Fettuccina: '菲图奇娜',
	'Fish Tails': '鱼尾',
	Gein: '盖因',
	Gomae: '戈梅',
	'Goon meow': '混混喵',
	Gopara: '戈帕拉',
	'Healer Haru': '治疗师春',
	'Honeymoon Helper': '蜜月助手',
	'Information Staff': '信息工作人员',
	'Instructor Argos': '教官阿尔戈斯',
	Kalu: '卡鲁',
	Kittie: '猫咪',
	'Kittie the Eraser': '重置猫咪',
	Kylick: '凯利克',
	Legalas: '莱加拉斯',
	Linguina: '林古伊娜',
	Locas: '洛卡斯',
	'Manufacturing Maniac': '制造狂人',
	'Master of Property': '属性大师',
	'Meow goon': '喵混混',
	Mom: '妈妈',
	'Mysterious Creature': '神秘生物',
	Mustachi: '穆斯塔奇',
	Odgnalam: '奥德格纳拉姆',
	'Perky Doram': '活泼的杜拉姆',
	Porto: '波尔图',
	Raket: '拉凯特',
	Rasmus: '拉斯穆斯',
	Red: '瑞德',
	'Refinery Owner Han': '精炼老板韩',
	'Refining Maniac': '精炼狂人',
	'Repair Man': '修理工',
	'Repairing Blacksmith': '修理铁匠',
	'Romantic Female': '浪漫女子',
	'Romantic Male': '浪漫男子',
	Scamp: '淘气鬼',
	Shepherd: '牧羊人',
	'Serious Doram': '严肃的杜拉姆',
	'Shaman meow': '萨满喵',
	'Shop Helper': '商店助手',
	Sirood: '西鲁德',
	'Smart Doram': '聪明的杜拉姆',
	Soup: '苏普',
	Tadde: '塔德',
	Tali: '塔莉',
	'Talkative Adventurer': '健谈的冒险者',
	'Talkative Kid': '健谈的小孩',
	'The brave third': '勇敢的老三',
	'The diligent second son': '勤奋的二儿子',
	'The sensitive-minded ela': '心思细腻的老大',
	'The skittish fourth': '胆小的老四',
	Tos: '托斯',
	'Tool Merchant': '工具商人',
	'Vigilante Guide': '治安队向导',
	'Vigilante Olio': '治安队员奥利奥',
	'Vigilante Penne': '巡逻队佩内',
	Vongolo: '翁戈洛',
	'Wedding Secretary': '婚礼秘书',
	'Workshop Manager': '工坊管理员',
	'Youngster meow': '年轻喵'
};
